#!/usr/bin/env bash
# Apply generated resource patches to a live Kubernetes cluster.
#
# Usage:
#   ./scripts/apply_patches.sh                        # apply all patches in patches/
#   ./scripts/apply_patches.sh patches/payment-service.yaml   # single workload
#   PATCHES_DIR=my-patches ./scripts/apply_patches.sh          # custom directory
#   DRY_RUN=1 ./scripts/apply_patches.sh               # preview only (kubectl --dry-run)
#
# Requirements:
#   - kubectl configured and pointing at the correct cluster context
#   - Patch files generated by: python main.py --source csv --output-dir patches/

set -euo pipefail

PATCHES_DIR="${PATCHES_DIR:-patches}"
DRY_RUN="${DRY_RUN:-0}"

# ── helpers ───────────────────────────────────────────────────────────────────

log()  { echo "[apply] $*"; }
warn() { echo "[apply] WARN: $*" >&2; }

kubectl_flags=()
if [[ "$DRY_RUN" == "1" ]]; then
    kubectl_flags+=("--dry-run=client")
    log "DRY RUN mode — no changes will be applied"
fi

# ── single file mode ──────────────────────────────────────────────────────────

if [[ $# -ge 1 ]]; then
    patch_file="$1"
    if [[ ! -f "$patch_file" ]]; then
        echo "Error: patch file not found: $patch_file" >&2
        exit 1
    fi
    name=$(basename "$patch_file" .yaml)
    namespace=$(grep -m1 'namespace:' "$patch_file" | awk '{print $2}')
    log "Patching $name in namespace ${namespace:-unknown}"
    kubectl patch deployment "$name" \
        -n "$namespace" \
        --patch-file "$patch_file" \
        "${kubectl_flags[@]+"${kubectl_flags[@]}"}"
    exit 0
fi

# ── all workloads ─────────────────────────────────────────────────────────────

if [[ ! -d "$PATCHES_DIR" ]]; then
    echo "Error: patches directory not found: $PATCHES_DIR" >&2
    echo "Run first: python main.py --source csv --output-dir $PATCHES_DIR" >&2
    exit 1
fi

shopt -s nullglob
patch_files=("$PATCHES_DIR"/*.yaml)

# Exclude summary.yaml — it is a report, not a patch
workload_files=()
for f in "${patch_files[@]}"; do
    [[ "$(basename "$f")" == "summary.yaml" ]] && continue
    workload_files+=("$f")
done

if [[ ${#workload_files[@]} -eq 0 ]]; then
    warn "No patch files found in $PATCHES_DIR"
    exit 0
fi

log "Applying ${#workload_files[@]} patch(es) from $PATCHES_DIR"

applied=0
failed=0

for patch_file in "${workload_files[@]}"; do
    name=$(basename "$patch_file" .yaml)
    namespace=$(grep -m1 'namespace:' "$patch_file" | awk '{print $2}')

    if kubectl patch deployment "$name" \
        -n "$namespace" \
        --patch-file "$patch_file" \
        "${kubectl_flags[@]+"${kubectl_flags[@]}"}" 2>&1; then
        (( applied++ ))
    else
        warn "Failed to patch $name — skipping"
        (( failed++ ))
    fi
done

log "Done: $applied applied, $failed failed"

# ── server-side apply (alternative) ──────────────────────────────────────────
# Uncomment to use server-side apply instead of strategic merge patch:
#
# kubectl apply --server-side -f "$PATCHES_DIR" "${kubectl_flags[@]+"${kubectl_flags[@]}"}"
